const my_Library= [
    {
        title:'Las aventuras de Tom Sawyer',
        author:'Autor: Mark Twain',
        gender:'Ficcion, Literatura Infantil',
        language:'Idioma: Ingles',
        price: 93100,
        format:'Ebook',
        isbn: '14789',
        description:'Es el relato de un chico huérfano que vive al cuidado de su tía Polly.',
        condition:'Nuevo',
        location:'Web',
        publication_date: 1876,
        editorial:'Editorial: Alma',
        pages: 320,
        availability: 'Disponible',
        stock: 5,
        image: 'https://res.cloudinary.com/dmlld7r9f/image/upload/v1718849347/las-aventuras-de-tom-sawyer_yvfabi.jpg'
    },
    {
        title:'El penultimo sueño',
        author:'Autor: Angela Becerra',
        gender:'Romance, Realismo Magico y Ficcion',
        language:'Idioma: Español',
        price: 38900 ,
        format:'Fisico',
        isbn: '9788408067221',
        description:'Joan Dolgut y Soledad Urdaneta representan en la Europa de entreguerras su particular Romeo y Julieta.',
        condition:'Usado',
        location:'Sena',
        publication_date: 2005,
        editorial:'Editorial: Booket',
        pages: 496,
        availability: 'No disponible',
        stock: 0,
        image:'https://res.cloudinary.com/dmlld7r9f/image/upload/v1718849401/penultimo-sueno__vmlwfj.jpg'
    },
    {
        title:'Cien años de soledad',
        author:'Autor: Gabriel García Márquez',
        gender:'Ficcion',
        language:'Idioma: Español',
        price: 25000 ,
        format:'Fisico',
        isbn: '978-84-376-0494-4',
        description:'La saga épica de la familia Buendía en el ficticio pueblo de Macondo.',
        condition:'Usado',
        location:'Sena',
        publication_date: 1967,
        editorial:'Editorial: Sudamericana',
        pages: 432,
        availability: 'No disponible',
        stock: 0,
        image: 'https://res.cloudinary.com/dmlld7r9f/image/upload/v1718849216/cien_a%C3%B1os_ocfalh.jpg'
    },
    {
        title:'La casa de los espiritus',
        author:'Autor: Isabel Allende',
        gender:'Ficcion',
        language:'Idioma: Español',
        price: 35000,
        format:'Fisico',
        isbn:'978-84-376-0495-1',
        description:'Una historia de amor, magia y tragedia que sigue a varias generaciones de la familia Trueba.',
        condition:'Usado',
        location:'Sena',
        publication_date: 1982,
        editorial:'Editorial: Plaza & Janes',
        pages: 528,
        availability: 'Disponible',
        stock: 2,
        image: 'https://res.cloudinary.com/dmlld7r9f/image/upload/v1718849340/la_casa_de_los_espiritus_d7s2tr.jpg'
    },
    {
        title:'Del Amor Y Otros Demonios',
        author:'Autor: Gabriel García Márquez',
        gender:'Ficcion',
        language:'Idioma: Español',
        price: 30000,
        format:'Fisico',
        isbn:' 978-84-376-0496-8',
        description:'Una historia de amor prohibido entre una joven y un sacerdote en la Colombia colonial.',
        condition:'Usado',
        location:'Sena',
        publication_date: 1994,
        editorial:'Editorial: Sudamericana',
        pages: 224,
        availability: 'Disponible',
        stock: 9,
        image: 'https://res.cloudinary.com/dmlld7r9f/image/upload/v1718849216/del_amor-al-odio_nhbscz.jpg'
    },
    {
        title:'El amor en los tiempos de colera',
        author:'Autor: Gabriel García Márquez',
        gender:'Ficcion',
        language:'Idioma: Español',
        price: 28000,
        format:'Fisico',
        isbn:'978-84-376-0497-5',
        description:'La historia de amor entre Fermina Daza y Florentino Ariza, que perdura a lo largo de décadas.',
        condition:'Usado',
        location:'Sena',
        publication_date: 1985,
        editorial:'Editorial: Sudamericana',
        pages: 384,
        availability: 'No disponible',
        stock: 0,
        image: 'https://res.cloudinary.com/dmlld7r9f/image/upload/v1718849234/el-amor-tiempo-colera_ugvh2b.jpg'
    },
    {
        title:'Noticia de un secuestro',
        author:'Autor: Gabriel García Márquez',
        gender:'Ficcion',
        language:'Idioma: Español',
        price: 32000,
        format:'Fisico',
        isbn:'978-84-376-0498-2',
        description:'Crónica del secuestro de importantes figuras colombianas por el cartel de Medellín.',
        condition:'Usado',
        location:'Sena',
        publication_date: 1996,
        editorial:'Editorial: Sudamericana',
        pages: 368,
        availability: 'Disponible',
        stock: 15,
        image: 'https://res.cloudinary.com/dmlld7r9f/image/upload/v1718849950/noticia_fblqzk.jpg'
    },
    {
        title:'Rosario Tijeras',
        author:'Autor: Jorge Franco',
        gender:'Ficcion',
        language:'Idioma: Español',
        price: 23000,
        format:'Ebook',
        isbn:'978-84-376-0499-9',
        description:'La historia de una joven sicaria en las calles de Medellín.',
        condition:'Nuevo',
        location:'Web',
        publication_date: 1999,
        editorial:'Editorial: Planeta',
        pages: 256,
        availability: 'Disponible',
        stock: 20,
        image: 'https://res.cloudinary.com/dmlld7r9f/image/upload/v1718849410/rosarioT_y4h9ea.jpg'
    },
    {
        title:'La virgen de los sicarios',
        author:'Autor: Fernando Vallejo',
        gender:'Ficcion',
        language:'Idioma: Español',
        price: 27000,
        format:'Fisico',
        isbn:'978-84-376-0500-2',
        description:'Un relato impactante sobre la violencia en Colombia, contado a través de la relación de un escritor homosexual y un joven sicario.',
        condition:'Usado',
        location:'Sena',
        publication_date: 1994,
        editorial:'Editorial: Alfaguara',
        pages: 224,
        availability: 'Disponible',
        stock: 10,
        image:'https://res.cloudinary.com/dmlld7r9f/image/upload/v1718849347/la-virgen-de-los-sicarios_pqqmao.jpg'
    },
    {
        title:'Relatos de un náufrago',
        author:'Autor: Gabriel García Márquez',
        gender:'Investigacion',
        language:'Idioma: Español',
        price: 20000,
        format:'Fisico',
        isbn:'978-84-376-0501-9',
        description:'La crónica verídica del naufragio de un marinero colombiano en el Caribe.',
        condition:'Usado',
        location:'Sena',
        publication_date: 1970,
        editorial:'Editorial: Tusquets Editores',
        pages: 160,
        availability: 'Disponible',
        stock: 5,
        image: 'https://res.cloudinary.com/dmlld7r9f/image/upload/v1718849403/relato-de-un-naufrago-garcia-marquez_dwhbls.jpg'
    },
    {
        title:'El general en su laberinto',
        author:'Autor: Gabriel García Márquez',
        gender:'Ficcion',
        language:'Idioma: Español',
        price: 29000,
        format:'Ebook',
        isbn:'978-84-376-0502-6',
        description:'La historia de los últimos días de Simón Bolívar, el libertador de América del Sur.',
        condition:'Nuevo',
        location:'Web',
        publication_date: 1989,
        editorial:'Editorial: Sudamericana',
        pages: 384,
        availability: 'No disponible',
        stock: 0,
        image: 'https://res.cloudinary.com/dmlld7r9f/image/upload/v1718849233/El_general_en_su_laberinto_a45jkl.jpg'
    },
    {
        title:'La vorágine',
        author:'Autor: José Eustasio Rivera',
        gender:'Novela',
        language:'Idioma: Español',
        price: 26000,
        format:'Fisico',
        isbn:'978-84-376-0503-3',
        description:'Una epopeya ambientada en la selva amazónica colombiana, que aborda temas como la explotación del caucho y la brutalidad de la naturaleza.',
        condition:'Usado',
        location:'Sena',
        publication_date: 1924,
        editorial:'Editorial: Estrañas Noches',
        pages: 352,
        availability: 'No disponible',
        stock: 0,
        image: 'https://res.cloudinary.com/dmlld7r9f/image/upload/v1718849348/La-Voragine_pvgieh.jpg'
    },
    {
        title:'Aura',
        author:'Autor: Carlos Fuentes',
        gender:'Ficción',
        language:'Idioma: Español',
        price: 24000,
        format:'Ebook',
        isbn:'978-84-376-0504-0',
        description:'Una historia de misterio y romance que se desarrolla en una misteriosa mansión en la Ciudad de México.',
        condition:'Nuevo',
        location:'Web',
        publication_date: 1962,
        editorial:'Editorial: Sudamericana',
        pages: 160,
        availability: 'Disponible',
        stock: 5,
        image: 'https://res.cloudinary.com/dmlld7r9f/image/upload/v1718848250/aura_s5roxa.png'


    },
    {
        title:'El alquimista',
        author:'Autor: Paulo Coelho',
        gender:'Ficción',
        language:'Idioma: Español',
        price: 31000,
        format:'Fisico',
        isbn:'978-84-376-0505-7',
        description:'La historia de Santiago, un joven pastor andaluz que viaja en busca de su tesoro personal.',
        condition:'Usado',
        location:'Sena',
        publication_date: 1988,
        editorial:'Editorial: Planeta',
        pages: 208,
        availability: 'Disponible',
        stock: 3,
        image: 'https://res.cloudinary.com/dmlld7r9f/image/upload/v1718849226/el_alquimista_lwgntc.jpg'
    },
    {
        title:'El coronel no tiene quien le escriba',
        author:'Autor: Gabriel García Márquez',
        gender:'Novela',
        language:'Idioma: Español',
        price: 27000,
        format:'Ebook',
        isbn:'978-84-376-0506-4',
        description:'La historia de un coronel retirado que espera ansiosamente la pensión que le deben por sus servicios en la guerra.',
        condition:'Usado',
        location:'Sena',
        publication_date: 1961,
        editorial:'Editorial: Sudamericana',
        pages: 112,
        availability: 'Disponible',
        stock: 2,
        image:'https://res.cloudinary.com/dmlld7r9f/image/upload/v1718849227/el_coronel_ngnhq5.jpg'
    },
    {
        title:'El olvido que seremos',
        author:'Autor: Héctor Abad Faciolince',
        gender:'Biografía',
        language:'Idioma: Español',
        price: 29000,
        format:'Fisico',
        isbn:'978-84-376-0507-1',
        description:'La emotiva biografía del padre del autor, Héctor Abad Gómez, un destacado médico y activista asesinado en Colombia.',
        condition:'Usado',
        location:'Sena',
        publication_date: 2006,
        editorial:'Editorial: Planeta',
        pages: 304,
        availability: 'Disponible',
        stock: 1,
        image:'https://res.cloudinary.com/dmlld7r9f/image/upload/v1718849240/el-olvido-que_-seremos_rdkiig.jpg'
    },
    {
        title:'La rebelión de las ratas',
        author:'Autor: Fernando Soto Aparicio',
        gender:'Novela',
        language:'Idioma: Español',
        price: 25000,
        format:'Ebook',
        isbn:'978-84-376-0508-8',
        description:'Una narración sobre la lucha de los habitantes de un barrio marginal en Bogotá contra la injusticia y la opresión.',
        condition:'Nuevo',
        location:'Web',
        publication_date: 1984,
        editorial:'Editorial: Planeta',
        pages: 288,
        availability: 'No disponible',
        stock: 0,
        image: 'https://res.cloudinary.com/dmlld7r9f/image/upload/v1718849340/la-rebelion-ratas_gpdsww.jpg'
    },
    {
        title:'La tejedora de coronas',
        author:'Autor: Germán Espinosa',
        gender:'Ficción',
        language:'Idioma: Español',
        price: 28000,
        format:'Fisico',
        isbn:'978-84-376-0509-5',
        description:'Una novela sobre la vida de una mujer misteriosa y sus encuentros con personajes históricos en la Colombia del siglo XIX.',
        condition:'Usado',
        location:'Sena',
        publication_date: 1982,
        editorial:'Editorial: Planeta',
        pages: 272,
        availability: 'Disponible',
        stock: 1,
        image:'https://res.cloudinary.com/dmlld7r9f/image/upload/v1718849411/tejedora_xby6do.jpg'
    },
    {
        title:'Los informantes',
        author:'Autor: Juan Gabriel Vásquez',
        gender:'Ficción',
        language:'Idioma: Español',
        price: 30000,
        format:'Ebook',
        isbn:'978-84-376-0510-1',
        description:'Una novela que explora los secretos y las traiciones en la sociedad colombiana contemporánea.',
        condition:'Nuevo',
        location:'Web',
        publication_date: 2004,
        editorial:'Editorial: Alfaguara',
        pages: 368,
        availability: 'Disponible',
        stock: 2,
        image:'https://res.cloudinary.com/dmlld7r9f/image/upload/v1718849394/los-informantes_euillw.jpg'
    },
    {
        title:'Los ejércitos',
        author:'Autor: Evelio Rosero',
        gender:'Ficción',
        language:'Idioma: Español',
        price: 26000,
        format:'Fisico',
        isbn:'978-84-376-0511-8',
        description:'La historia de un anciano que vive en un pueblo colombiano asolado por la violencia y la presencia de los grupos armados.',
        condition:'Usado',
        location:'Sena',
        publication_date: 2006,
        editorial:'Editorial: Anagrama',
        pages: 208, 
        availability: 'Disponible',
        stock: 1,
        image: 'https://res.cloudinary.com/dmlld7r9f/image/upload/v1718849217/ejercitos_dtsvi1.jpg'
    }
]